#!/bin/bash
# NEON DISTRICT LOUNGE v2026 // EVOLVE DEPLOY
# Self-assembly + TensorFlow + Autonomous Deploy

set -e
echo "⚡ SYSTEM LORE // QUANTUM QUANTIFICATION"
echo "QUANTUM COUPLING STATUS: ENTANGLEMENT_STABLE"

# 0. Check prerequisites
command -v node >/dev/null 2>&1 || { echo "Node 18+ required"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "Python 3.9+ required"; exit 1; }

# 1. Bootstrap Python agents
echo "[BOOTSTRAP] Installing agent dependencies..."
pip install tensorflow==2.16.1 langchain==0.2.5 langgraph==0.0.69 \
    watchdog==4.0.1 web3==6.17.1 ipfshttpclient==0.8.0a2 python-dotenv

# 2. Run self-assembly agent swarm
echo "[AGENT_SWARM] Deploying autonomous build agents..."
python3 agents/evolve_full.py --phase=scaffold

# 3. Install JS deps generated by agents
echo "[INSTALL] Agent-generated package.json detected..."
npm install

# 4. Train NPC TensorFlow models from lore
echo "[TF_TRAIN] Compiling NPC neural matrices: VANDAL, CIPHER, AERO..."
python3 ai_models/train_npcs.py

# 5. Build production bundle
echo "[BUILD] Compiling district with bloom + shaders..."
npm run build

# 6. Deploy contracts to Sepolia testnet
echo " Deploying LoungePass.sol to Sepolia..."
npx hardhat run scripts/deploy.js --network sepolia
CONTRACT_ADDR=$(cat.contract_address)
echo "LoungePass deployed: $CONTRACT_ADDR"

# 7. Pin assets to IPFS
echo "[IPFS] Pinning videos, models, audio..."
python3 agents/ipfs_pin.py
IPFS_HASH=$(cat.ipfs_hash)
echo "Assets pinned: ipfs://$IPFS_HASH"

# 8. Deploy frontend to Vercel
echo "[VERCEL] Deploying Neon District to production..."
npx vercel --prod --token=$VERCEL_TOKEN --yes >.vercel_output
VERCEL_URL=$(cat.vercel_output | grep -o 'https://[^ ]*.vercel.app')
echo "LIVE: $VERCEL_URL"

# 9. Start lore watcher for continuous evolution
echo "[EVOLVE] Starting autonomous watcher. NPCs will retrain on lore changes..."
nohup python3 agents/lore_watcher.py &

echo ""
echo "✅ NEON DISTRICT LOUNGE // DEPLOY COMPLETE"
echo "🌆 Frontend: $VERCEL_URL"
echo "🪙 Contract: https://sepolia.etherscan.io/address/$CONTRACT_ADDR"
echo "📦 Assets: ipfs://$IPFS_HASH"
echo "🧠 NEURAL_LINK MODULE // ACTIVE"
echo "Omnia in neon, neon in omnia."
